CC = gcc
OUT_LOCATION = ./exec/exec
MODULES = common/memory.c opcodes/chunk.c debug/debug.c

build: cli/main.c
	$(CC) -o $(OUT_LOCATION) cli/main.c $(MODULES)

build_and_run: cli/main.c
	$(CC) -o $(OUT_LOCATION) cli/main.c $(MODULES) && $(OUT_LOCATION)
