CC = gcc
OUT_LOCATION = ./exec/exec
OPTIONS = -O2
MODULES = common/memory.c opcodes/chunk.c debug/debug.c constants/value.c vm/vm.c vm/vm_helpers.c compiler/compiler.c scanner/scanner.c

build: cli/main.c
	$(CC) -o $(OUT_LOCATION) cli/main.c $(MODULES)

build_and_run: cli/main.c
	$(CC) $(OPTIONS) -o $(OUT_LOCATION) cli/main.c $(MODULES) && $(OUT_LOCATION)

bench:
	$(CC) $(OPTIONS) -o $(OUT_LOCATION) cli/main.c $(MODULES) && time $(OUT_LOCATION)


TEST_OPTIONS = -Iunity/src -Isrc
TEST_MODULES = tests/test_chunk.c tests/unity/unity.c
TEST_OUT = tests/exec/tests

test: tests/lib.c
	$(CC) tests/lib.c $(TEST_MODULES) $(MODULES) $(TEST_OPTIONS) -o $(TEST_OUT) && $(TEST_OUT)
